In [1]:
import numpy as np

from piqp import SolverBase, Data, Settings


In [2]:
P = np.array([[4.0, 1.0], [1.0, 2.0]])
c = np.array([1.0, 1.0])
A = np.array([[1.0, 1.0]])
b = np.array([1.0])
G = np.array([[1.0, 0.0], [0.0, 1.0], [-1.0, 0.0], [0.0, -1.0]])
h_u = np.array([0.5, 0.5, 1.0, 1.0])
h_l = np.array([-100., -100., -0.5, -0.5])
x_u = 100 * np.ones(2)
x_l = -100 * np.ones(2)

data = Data(P, c, A, b, G, h_u, h_l, x_u, x_l)

solver = SolverBase()
solver.setup(P, c, A, b, G, h_u, h_l, x_u, x_l)
# solver.settings.verbose = True
result = solver.solve()

[-16.66515567 -16.66598891]
[-343311.44575917]
[-335848.44330517 -335840.11093566 -174151.55669483 -174159.88906434]
[-669151.55669483 -669159.88906434  159151.55669483  159159.88906434]
[2.000101e+10 2.000101e+10]
[1.999901e+10 1.999901e+10]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[-0. -0.]
[-0. -0.]


In [11]:
import jax

@jax.jit
def f(x, out):
    out[0] = x + 1    # ❌ illegal in JAX

b = [0.]
f(10.0, b)
print(b[0])

0.0
