In [1]:
import numpy as np

from piqp import SolverBase, Data, Settings

%load_ext autoreload
%autoreload 2

In [2]:
P = np.array([[4.0, 1.0], [1.0, 2.0]])
c = np.array([1.0, 1.0])
A = np.array([[1.0, 1.0]])
b = np.array([1.0])
G = np.array([[1.0, 0.0], [0.0, 1.0], [-1.0, 0.0], [0.0, -1.0]])
h_u = np.array([0.5, 0.5, 1.0, 1.0])
h_l = np.array([-100., -100., -0.5, -0.5])
x_u = 100 * np.ones(2)
x_l = -100 * np.ones(2)

P = np.array([[6.0, 0.0], [0.0, 4.0]])
c = np.array([-1.0, -4.0])
A = np.array([[1.0, -2.0]])
b = np.array([1.0])
G = np.array([[1.0, -1.0], [2.0, 0.0]])
h_u = np.array([0.2, -1.0])
h_l = np.array([-10.0, -10.0])
x_l = np.array([-1.0, -1.0])
x_u = np.array([1.0, 1.0])


In [3]:
# import piqp
# print("PIQP version:", piqp.__version__)
# piqp_solver = piqp.SparseSolver()
# piqp_solver.settings.verbose = True
# piqp_solver.setup(P, c, A, b, G, h_l, h_u, x_l, x_u)
# status = piqp_solver.solve()
# print("Status: ", status)
# print("Optimal primal solution:", piqp_solver.result.x)

In [4]:
data = Data(P, c, A, b, G, h_u, h_l, x_u, x_l)

solver = SolverBase()
solver.settings.debug = False
solver.settings.verbose = True
solver.settings.max_iter = 10
solver.setup(P, c, A, b, G, h_u, h_l, x_u, x_l)
result = solver.solve()

iter   prim_obj        dual_obj        duality_gap    prim_res       dual_res       rho          delta        mu           p_step    d_step

Initial point set. Starting iterations...
 Variables:
  x:    [-1.27220693 -1.13559498]
  y:    [-10.16958374]
  z_u:  [2.97452787 2.45976784]
  z_l:  [0.91394408 1.14522165]
  z_bu: [1. 1.]
  z_bl: [1. 1.]
  s_u:  [1. 1.]
  s_l:  [1. 1.]
  s_bu: [1. 1.]
  s_bl: [1. 1.]
  0    1.32493e+01   -2.69249e+01    4.01742e+01    2.97449e+00    1.51889e+01    1.000e-06    1.000e-04    9.849e+00    0.0000    0.0000
  1    4.64224e+00   -3.14597e-01    4.95684e+00    2.96934e-01    6.75700e-01    1.047e-07    1.047e-05    1.031e+00    0.9002    0.9900
  2    5.24761e+00    5.19958e+00    4.80279e-02    6.05552e-02    1.18343e-01    8.707e-09    8.707e-07    8.575e-02    0.7961    0.9900
  3    9.98700e+00    2.65538e+00    7.33161e+00    4.63953e-03    2.89205e+00    8.707e-09    8.707e-07    4.460e-01    0.9292    0.0267
  4    6.14401e+00    4.60413e+00   

In [5]:
import numpy as np
from scipy.sparse import csr_matrix

A = csr_matrix(np.random.randn(8, 8))
# A_bsr = A.tobsr(blocksize=(2, 2))
A_bsr = A.tobsr()

print(A_bsr.blocksize)   # (2, 2)
print(A_bsr.data.shape) # (n_blocks, 2, 2)

(4, 4)
(4, 4, 4)


In [6]:
import numpy as np
from scipy.sparse import block_diag

# Three dense blocks (2x2 each)
B1 = np.array([[1., 2.],
               [3., 4.]])
B2 = np.array([[5., 0.],
               [0., 6.]])
B3 = np.array([[7., 8.],
               [9., 10.]])

# Build sparse block-diagonal matrix (CSR by default)
A_csr = block_diag((B1, B2, B3), format="csr")

print(A_csr.shape)
# (6, 6)

# A_bsr = A_csr.tobsr(blocksize=(2, 2))
A_bsr = A_csr.tobsr()
print("Block size:", A_bsr.blocksize)
print("Number of blocks:", A_bsr.data.shape[0])
print("BSR data:")
print(A_bsr.data)

(6, 6)
Block size: (2, 2)
Number of blocks: 3
BSR data:
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  0.]
  [ 0.  6.]]

 [[ 7.  8.]
  [ 9. 10.]]]
