# Getting started with cuPIQP

## Problem formulation

CuPIQP solves (convex) **quadratic programs (QPs)** in the following form:

$$
\begin{aligned}
\min_{x}\quad & \tfrac{1}{2}\, x^\top P x + c^\top x \\
\mathrm{s.t}\quad & A x = b, \\
                  & h_l \le G x \le h_u, \\
                  & x_l \le x \le x_u,
\end{aligned}
$$

where

| symbol | meaning | shape |
|---|---|---|
| $P = P^\top \succeq 0$ | quadratic cost (symmetric positive semidefinite) | $n \times n$ |
| $c$ | linear cost | $n$ |
| $A,\, b$ | equality constraints | $p \times n$, $\;p$ |
| $G,\, h_l,\, h_u$ | two-sided inequality constraints | $m \times n$, $\;m$, $\;m$ |
| $x_l,\, x_u$ | element-wise box bounds on $x$ | $n$, $\;n$ |

**Unbounded entries** (one-sided constraints, free variables) are set to $\pm\infty$
(`np.inf` or `wp.inf`); cuPIQP detects these and ignores the corresponding rows/bounds
automatically.

All problem data lives **on the GPU**. Dense data is passed as GPU arrays: `warp.array`,
as used in this notebook, or any CUDA array (CuPy, PyTorch, JAX). Sparse matrices are
passed as CSR triples `(indptr, indices, values)` of GPU arrays. cuPIQP never casts
dtypes or copies host data implicitly, so the data must already be on the GPU in the
solver's dtype (`wp.float64` by default).

cuPIQP is **natively batched** -- it solves a batch of $B$ independent QPs in a
*single* GPU call. This notebook builds a batch in which **every problem is a little
different** (including one that is **infeasible**), solves it with both the dense and
the sparse backend, and prints the per-problem solver status.

In [1]:
import numpy as np
import warp as wp
from cupiqp import DenseSolver, SparseSolver, Status

## Example QPs

We consider the following problem:

$$
\begin{aligned}
\min_{x_1,\,x_2}\quad & \tfrac12\bigl(6 x_1^2 + 4 x_2^2\bigr) - x_1 - 4 x_2 \\
\text{s.t.}\quad
  & x_1 - 2 x_2 = 1, \\
  & x_1 - x_2 \leq 0.2, \\
  & 2x_1 \le -1, \\
  & \theta \le x_1 \le 1,
\end{aligned}
$$

where $\theta$ is the lower bound on $x_1$ which varies among problems in the batch. In this example, we create a batch of $B=4$ problems. For simplicity, we assign different values of $\theta$ to each problem while keeping other data the same:

| problem | 0 | 1 | 2 | 3 |
|---|---|---|---|---|
| $\theta$ | $-\infty$ | $-2.0$ | $-1.0$ | $2.0$ |

Problem 3 is infeasible since the bounds of $x_1$ becomes $2 \leq x_1 \leq 1$, so
the box $2.0 \le x_1 \le 1$ is empty. 

`solver.result.x` then has shape `(B, n)` and `solver.result.info.status` is a list of
$B$ statuses (one per problem) -- so the infeasible problem reports a different status
from the rest.

In [2]:
theta = np.array([-np.inf, -2.0, -1.0, 2.0])

# --- Template data ---
# quadratic + linear cost
P = np.array([[6.0, 0.0],
              [0.0, 4.0]])
c = np.array([-1.0, -4.0])

# equality constraint:  A x = b
A = np.array([[1.0, -2.0]])
b = np.array([1.0])

# two-sided inequalities:  h_l <= G x <= h_u   (use -inf / +inf for one-sided)
G   = np.array([[1.0, -1.0],
                [2.0,  0.0]])
h_l = np.array([-np.inf, -np.inf])
h_u = np.array([0.2, -1.0])

# box bounds:  x_l <= x <= x_u
x_l = np.array([-1.0, -np.inf])
x_u = np.array([ 1.0,  np.inf])


# --- Build batched data ---
B = 4  # batch size

# replicate the template along the leading batch dimension -> (B, ...) on the GPU;
# only the box lower bound x_l differs between the problems
stack = lambda M: wp.from_numpy(np.stack([M] * B), dtype=wp.float64, device="cuda")
P_batch, c_batch, A_batch, b_batch, G_batch = stack(P), stack(c), stack(A), stack(b), stack(G)
h_l_batch, h_u_batch, x_u_batch = stack(h_l), stack(h_u), stack(x_u)
x_l_batch = wp.array([
    [theta[0], -wp.inf],
    [theta[1], -wp.inf],
    [theta[2], -wp.inf],
    [theta[3], -wp.inf],  # infeasible!
	],
    dtype=wp.float64,
    device="cuda"
    )


In [3]:
print(P_batch.shape)
print(P_batch.dtype)
print(type(P_batch))
print(np.stack([P] * B).shape)
print(wp.from_numpy(np.stack([P] * B)))

(4, 2, 2)
<class 'warp._src.types.float64'>
<class 'warp._src.types.array'>
(4, 2, 2)
[[[6. 0.]
  [0. 4.]]

 [[6. 0.]
  [0. 4.]]

 [[6. 0.]
  [0. 4.]]

 [[6. 0.]
  [0. 4.]]]


## Dense Solver

`DenseSolver` works with **dense** GPU arrays for `P`, `A`, `G`. Every argument of `setup` is
either **batched**, with a leading batch axis (one value per problem), or **shared**, in the
shape of one problem (the same value for every problem):

| array | shared | batched |
|---|---|---|
| `P` | `(n, n)` | `(B, n, n)` |
| `c`, `x_l`, `x_u` | `(n,)` | `(B, n)` |
| `A` / `G` | `(p, n)` / `(m, n)` | `(B, p, n)` / `(B, m, n)` |
| `b`, `h_l`, `h_u` | `(p,)` / `(m,)` | `(B, p)` / `(B, m)` |

`setup` reads the batch size `B` from the batched arguments; there is no `batch_size`
argument. Since `setup` already holds the data of all `B` problems, `solve()` can be called
right away. Read the per-problem solution and status off `solver.result`. To re-solve with
new values of the same structure, call `update(...)` with the changed arguments (same two
forms) and `solve()` again.

In [4]:
solver_dense = DenseSolver()
solver_dense.settings.verbose = True

# setup: here every argument is batched (B, ...), and the leading axis sets B = 4.
# Only x_l really differs, so the others could also be passed shared, e.g.
# P=wp.array(P, dtype=wp.float64, device="cuda").
# h_l is all -inf, so it could also be omitted.
solver_dense.setup(P=P_batch, c=c_batch, A=A_batch, b=b_batch, G=G_batch,
                   h_l=h_l_batch, h_u=h_u_batch, x_l=x_l_batch, x_u=x_u_batch)
status_dense = solver_dense.solve()  # returns a list of length B containing the status of each individual problem

----------------------------------------------------------
       cuPIQP v0.1.0 - GPU-accelerated PIQP solver        
                    (c) Fenglong Song                     
   Ecole Polytechnique Federale de Lausanne (EPFL) 2026   
----------------------------------------------------------
dense backend:
batch size B = 4
variables n = 2
equality constraints p = 1
inequality constraints m = 2
inequality lower bounds n_h_l = 2
inequality upper bounds n_h_u = 2
variable lower bounds n_x_l = 2
variable upper bounds n_x_u = 2

iter  solved       gap_max     p_res_max     d_res_max     rho_max   delta_max      mu_max  p_step  d_step
   0     0/4   1.90819e+01   2.69408e+00   7.32911e+00   1.000e-06   1.000e-04   1.652e+00  0.0000  0.0000


   1     0/4   2.16919e+03   2.52134e+00   4.41792e+00   1.000e-07   1.000e-05   2.362e+01  0.0648  0.9323


   2     0/4   1.48750e+06   2.44501e+00   1.44267e+00   5.000e-08   5.000e-06   1.140e+03  0.1477  0.1575


   3     0/4   3.76528e+06   2.45375e+00   1.31190e-01   5.000e-09   2.500e-06   3.807e+03  0.1401  0.9900


   4     0/4   8.11153e+06   2.31340e+00   1.31190e-03   5.000e-10   2.500e-07   1.391e+05  0.9900  0.9900


   5     0/4   1.23081e+08   3.39747e+00   5.39997e-01   1.000e-10   1.250e-07   1.202e+07  0.7501  0.9900


   6     0/4   1.88256e+08   2.15494e+00   5.39996e-03   1.000e-10   1.250e-08   1.784e+07  0.9900  0.9900


   7     3/4   3.70299e+09   5.81318e+00   5.38975e-05   1.000e-10   6.250e-09   1.227e+09  0.9900  0.9900


   8     3/4   4.05562e+09   2.50890e+00   5.96046e-07   1.000e-10   6.250e-10   3.923e+08  0.9900  0.9900


   9     3/4   4.81383e+10   3.49580e+00   3.73679e-01   1.000e-10   3.125e-10   5.125e+09  0.8869  0.9900


  10     3/4   7.80691e+10   2.22696e+00   3.73268e-03   1.000e-10   1.000e-10   8.232e+09  0.9900  0.9900


  11     3/4   3.47117e+11   3.39258e+00   1.89339e-01   1.000e-10   1.000e-10   3.335e+10  0.9378  0.9900


  12     3/4   2.80611e+11   2.48835e+00   1.89209e-03   1.000e-10   1.000e-10   2.485e+09  0.9900  0.9900


  13     3/4   4.73714e+11   2.46534e+00   2.76584e-03   1.000e-10   1.000e-10   1.842e+09  0.9900  0.9685


  14     3/4   4.76899e+11   2.42384e+00   3.73762e-05   1.000e-10   1.000e-10   1.856e+07  0.9900  0.9900


  15     3/4   4.76931e+11   2.42342e+00   3.73762e-05   1.000e-10   1.000e-10   1.856e+05  0.9900  0.9900


  16     3/4   4.76931e+11   2.42342e+00   7.47525e-05   1.000e-10   1.000e-10   1.856e+03  0.9900  0.9900


  17     3/4   4.76931e+11   2.42342e+00   7.62939e-06   1.000e-10   1.000e-10   1.856e+01  0.9900  0.9900


  18     4/4   4.76931e+11   2.42342e+00   3.73762e-05   1.000e-10   1.000e-10   1.857e-01  0.9900  0.9900



Finished in 18 iterations


  Solved:              3/4


  Primal infeasible:   1/4


### Extract the results
The result of the optimization can be obtained from the `solver.result` object, for example:

- `solver.result.info.status`: status of the problems
- `solver.result.x`: primal solution
- `solver.result.y`: dual solution of equality constraints
- `solver.result.z_l`: dual solution of lower inequality constraints
- `solver.result.z_u`: dual solution of upper inequality constraints
- `solver.result.z_bl`: dual solution of lower bound box constraints
- `solver.result.z_bu`: dual solution of upper bound box constraints

For example,

In [5]:
# status can be obtained from solver.result.info
status_dense = solver_dense.result.info.status  # list of length B
print(f'\nresult.info.status is a {type(solver_dense.result.info.status)} object with length B:')
print(solver_dense.result.info.status)
print()


# iteration numbers
for i in range(B):
    print(f"problem {i}:  theta = {float(theta[i]):.1f}   status = {solver_dense.result.info.status[i].name:<24}   iter = {solver_dense.result.info.iter[i]}")


# solutions
print(f'\nresult.x is a {type(solver_dense.result.x)} object with shape {solver_dense.result.x.shape}, same as (B, n)')
print(f'result.y is a {type(solver_dense.result.y)} object with shape {solver_dense.result.y.shape}, same as (B, p)')
print(f'result.z_l is a {type(solver_dense.result.z_l)} object with shape {solver_dense.result.z_l.shape}, same as (B, m) if h_l is not None in setup() otherwise (B, 0)')
print(f'result.z_u is a {type(solver_dense.result.z_u)} object with shape {solver_dense.result.z_u.shape}, same as (B, m) if h_u is not None in setup() otherwise (B, 0)')
print(f'result.z_bl is a {type(solver_dense.result.z_bl)} object with shape {solver_dense.result.z_bl.shape}, same as (B, n) if x_l is not None in setup() otherwise (B, 0)')
print(f'result.z_bu is a {type(solver_dense.result.z_bu)} object with shape {solver_dense.result.z_bu.shape}, same as (B, n) if x_u is not None in setup() otherwise (B, 0)')


# objectives: (B,) warp arrays
print(f'\nresult.info.primal_obj is a {type(solver_dense.result.info.primal_obj)} object with shape {solver_dense.result.info.primal_obj.shape}')
print(f'result.info.dual_obj is a {type(solver_dense.result.info.dual_obj)} object with shape {solver_dense.result.info.dual_obj.shape}')


result.info.status is a <class 'list'> object with length B:
[<Status.CUPIQP_SOLVED: 0>, <Status.CUPIQP_SOLVED: 0>, <Status.CUPIQP_SOLVED: 0>, <Status.CUPIQP_PRIMAL_INFEASIBLE: 2>]

problem 0:  theta = -inf   status = CUPIQP_SOLVED              iter = 7
problem 1:  theta = -2.0   status = CUPIQP_SOLVED              iter = 7
problem 2:  theta = -1.0   status = CUPIQP_SOLVED              iter = 7
problem 3:  theta = 2.0   status = CUPIQP_PRIMAL_INFEASIBLE   iter = 18

result.x is a <class 'warp._src.types.array'> object with shape (4, 2), same as (B, n)
result.y is a <class 'warp._src.types.array'> object with shape (4, 1), same as (B, p)
result.z_l is a <class 'warp._src.types.array'> object with shape (4, 2), same as (B, m) if h_l is not None in setup() otherwise (B, 0)
result.z_u is a <class 'warp._src.types.array'> object with shape (4, 2), same as (B, m) if h_u is not None in setup() otherwise (B, 0)
result.z_bl is a <class 'warp._src.types.array'> object with shape (4, 2), same as

To copy a `wp.array` to host, use the `numpy()` method:

In [6]:
# result.x is a warp.array on the GPU; .numpy() copies it to the host:
x_dense_host = solver_dense.result.x.numpy()  # (B, n) numpy array
print(f'\nresult.x.numpy() is a {type(x_dense_host)} object with shape {x_dense_host.shape}')


result.x.numpy() is a <class 'numpy.ndarray'> object with shape (4, 2)


## Sparse solver

### CSR triples: one sparsity pattern, per-problem values

All problems in a sparse batch share **one** sparsity pattern per matrix. `SparseSolver.setup`
takes each of $P, A, G$ as a CSR triple `(indptr, indices, values)`:

- `indptr` and `indices` are 1-D integer arrays (`int32` or `int64`) describing the pattern of
  one problem, with column indices sorted within each row (call `sort_indices()` on a scipy
  matrix first if needed). They may be on the **host or the device**: a host pattern, e.g.
  straight from scipy, is checked and copied to the device once by `setup`;
- `values` must be on the **device** and holds the nonzeros in the order of `indices`:
  `(nnz,)` shared by every problem, or `(B, nnz)` with one row per problem.

The vectors $c, b, h_l, h_u, x_l, x_u$ follow the same shared / batched rule as for the dense
solver. As before, `setup` reads `B` from the batched arguments and `solve()` can be called
right away. The pattern is fixed at `setup`; `update` then takes only new **nonzero values**,
e.g. `update(P=P_values)` with `P_values` of shape `(nnz,)` or `(B, nnz)`.

In [ ]:
from scipy.sparse import csr_matrix

def prepare_sparse_mat_args(M: np.ndarray):
    """CSR triple (indptr, indices, values) of the host matrix M: the pattern stays on the
    host, the values are repeated for the B problems on the device."""
    M_sp = csr_matrix(M)
    args = (
        M_sp.indptr,                                                                # shared indptr on the host (or device), shape: (rows+1, )
        M_sp.indices,                                                               # shared indices on the host (or device), shape: (nnz, )
        wp.from_numpy(np.tile(M_sp.data, (B, 1)), dtype=wp.float64, device="cuda")  # all nnz values on the device, shape: (B, nnz)
        )
    return args

Setup solver and solve:

In [8]:
solver_sparse = SparseSolver()
solver_sparse.settings.verbose = True

# setup: matrix values are (B, nnz) and the vectors (B, k), one row per problem.
# Values shared by every problem could also be passed as (nnz,), e.g. csr_matrix(P).data.
solver_sparse.setup(
    P=prepare_sparse_mat_args(P), c=c_batch,
    A=prepare_sparse_mat_args(A), b=b_batch,
    G=prepare_sparse_mat_args(G), h_l=h_l_batch, h_u=h_u_batch,
    x_l=x_l_batch, x_u=x_u_batch,
)

status_sparse = solver_sparse.solve()

for i in range(B):
    print(f"problem {i}:  theta = {float(theta[i]):.1f}   status = {solver_sparse.result.info.status[i].name:<24}   iter = {solver_sparse.result.info.iter[i]}")

----------------------------------------------------------
       cuPIQP v0.1.0 - GPU-accelerated PIQP solver        
                    (c) Fenglong Song                     
   Ecole Polytechnique Federale de Lausanne (EPFL) 2026   
----------------------------------------------------------
sparse backend:
batch size B = 4
variables n = 2, nnz(P) = 2
equality constraints p = 1, nnz(A) = 2
inequality constraints m = 2, nnz(G) = 3
inequality lower bounds n_h_l = 2
inequality upper bounds n_h_u = 2
variable lower bounds n_x_l = 2
variable upper bounds n_x_u = 2

iter  solved       gap_max     p_res_max     d_res_max     rho_max   delta_max      mu_max  p_step  d_step
   0     0/4   1.90819e+01   2.69408e+00   7.32911e+00   1.000e-06   1.000e-04   1.652e+00  0.0000  0.0000


   1     0/4   2.16919e+03   2.52134e+00   4.41792e+00   1.000e-07   1.000e-05   2.362e+01  0.0648  0.9323


   2     0/4   1.48750e+06   2.44501e+00   1.44267e+00   5.000e-08   5.000e-06   1.140e+03  0.1477  0.1575


   3     0/4   3.76528e+06   2.45375e+00   1.31190e-01   5.000e-09   2.500e-06   3.807e+03  0.1401  0.9900


   4     0/4   8.11153e+06   2.31340e+00   1.31190e-03   5.000e-10   2.500e-07   1.391e+05  0.9900  0.9900


   5     0/4   1.23081e+08   3.39747e+00   5.39997e-01   1.000e-10   1.250e-07   1.202e+07  0.7501  0.9900


   6     0/4   1.88256e+08   2.15494e+00   5.39996e-03   1.000e-10   1.250e-08   1.784e+07  0.9900  0.9900


   7     3/4   3.70299e+09   5.81318e+00   5.39869e-05   1.000e-10   6.250e-09   1.227e+09  0.9900  0.9900


   8     3/4   4.05562e+09   2.50890e+00   4.76837e-07   1.000e-10   6.250e-10   3.923e+08  0.9900  0.9900


   9     3/4   4.81383e+10   3.49580e+00   3.73679e-01   1.000e-10   3.125e-10   5.125e+09  0.8869  0.9900


  10     3/4   7.80691e+10   2.22696e+00   3.73650e-03   1.000e-10   1.000e-10   8.232e+09  0.9900  0.9900


  11     3/4   3.47117e+11   3.39258e+00   1.89350e-01   1.000e-10   1.000e-10   3.335e+10  0.9378  0.9900


  12     3/4   2.80611e+11   2.48835e+00   1.88828e-03   1.000e-10   1.000e-10   2.485e+09  0.9900  0.9900


  13     3/4   4.73714e+11   2.46534e+00   2.84059e-03   1.000e-10   1.000e-10   1.842e+09  0.9900  0.9685


  14     3/4   4.76899e+11   2.42384e+00   3.73762e-05   1.000e-10   1.000e-10   1.856e+07  0.9900  0.9900


  15     3/4   4.76931e+11   2.42342e+00   7.62939e-06   1.000e-10   1.000e-10   1.856e+05  0.9900  0.9900


  16     3/4   4.76931e+11   2.42342e+00   3.73762e-05   1.000e-10   1.000e-10   1.856e+03  0.9900  0.9900


  17     3/4   4.76931e+11   2.42342e+00   3.73762e-05   1.000e-10   1.000e-10   1.856e+01  0.9900  0.9900


  18     4/4   4.76931e+11   2.42342e+00   7.62939e-06   1.000e-10   1.000e-10   1.857e-01  0.9900  0.9900



Finished in 18 iterations


  Solved:              3/4


  Primal infeasible:   1/4


problem 0:  theta = -inf   status = CUPIQP_SOLVED              iter = 7
problem 1:  theta = -2.0   status = CUPIQP_SOLVED              iter = 7
problem 2:  theta = -1.0   status = CUPIQP_SOLVED              iter = 7
problem 3:  theta = 2.0   status = CUPIQP_PRIMAL_INFEASIBLE   iter = 18


## Verify the solution consistency

In [9]:
dense_status  = [st.name for st in solver_dense.result.info.status]
sparse_status = [st.name for st in solver_sparse.result.info.status]

# the two backends should agree on every problem's status ...
assert dense_status == sparse_status

# ... and on the problems that solved, the dense and sparse optima agree.
solved = [i for i, st in enumerate(solver_dense.result.info.status)
          if st == Status.CUPIQP_SOLVED]
assert np.allclose(
    solver_dense.result.x.numpy()[solved], 
    solver_sparse.result.x.numpy()[solved], 
    atol=1e-8
    )